#!/bin/bash

echo "🚀 RoofReady Railway Deployment Script"
echo "======================================"
echo ""
echo "This script will guide you through deploying the fulfillment service."
echo ""

echo "📋 Prerequisites:"
echo "1. Railway account (https://railway.app)"
echo "2. GitHub account with roofready repository"
echo "3. Stripe API keys (you have these)"
echo ""

read -p "Press Enter when you're logged into Railway..."

echo ""
echo "🔧 Step 1: Install Railway CLI"
echo "-----------------------------"
echo "Run this command in your terminal:"
echo ""
echo "npm install -g @railway/cli"
echo ""
read -p "Press Enter after installing Railway CLI..."

echo ""
echo "🔑 Step 2: Login to Railway"
echo "--------------------------"
echo "Run:"
echo ""
echo "railway login"
echo ""
echo "Follow the browser prompt to authenticate."
echo ""
read -p "Press Enter after logging in..."

echo ""
echo "🚂 Step 3: Create New Project"
echo "----------------------------"
echo "Run:"
echo ""
echo "railway init --name roofready-fulfillment"
echo ""
echo "Select 'Empty Project' when prompted."
echo ""
read -p "Press Enter after creating project..."

echo ""
echo "⚙️ Step 4: Set Environment Variables"
echo "----------------------------------"
echo "Copy and run these commands ONE BY ONE:"
echo ""
echo "railway variables set STRIPE_PUBLISHABLE_KEY=pk_live_51STxu4F4HWFknWFw05SbItafoAKLmCAOOZLaHY3aWJuBAmHN3uo2cPMXk4AHeLCYEAIP3Oe98ZcoGtPZZRfCUkzU00cde8vOvG"
echo ""
echo "railway variables set STRIPE_SECRET_KEY=YOUR_SECRET_KEY_HERE"
echo ""
echo "railway variables set STRIPE_PRICE_STARTER=price_1TMBWCF4HWFknWFwSWv5Snum"
echo "railway variables set STRIPE_PRICE_PRO=price_1TMBriF4HWFknWFwwwciIvgM"
echo "railway variables set STRIPE_PRICE_TEAM=price_1TMByGF4HWFknWFw3j9txtCU"
echo ""
echo "railway variables set APP_URL=https://roofready-seven.vercel.app"
echo "railway variables set SUPABASE_URL=https://wolnyokijwtrxkyluxrj.supabase.co"
echo "railway variables set SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvbG55b2tpand0cnhreWx1eHJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwODgwMTEsImV4cCI6MjA5MTY2NDAxMX0.n0HAtBGNSKuK8yV8qQ4p85JJy3UquAM-MPpfw7OK8jY"
echo ""
echo "railway variables set NODE_ENV=production"
echo "railway variables set PORT=3002"
echo ""
read -p "Press Enter after setting ALL variables..."

echo ""
echo "📦 Step 5: Deploy Service"
echo "------------------------"
echo "Run:"
echo ""
echo "railway up"
echo ""
echo "This will deploy the fulfillment service."
echo "It may take 2-3 minutes to build and deploy."
echo ""
read -p "Press Enter to start deployment..."

echo ""
echo "🌐 Step 6: Get Webhook URL"
echo "-------------------------"
echo "After deployment completes, run:"
echo ""
echo "railway status"
echo ""
echo "Look for the URL like: https://roofready-fulfillment.up.railway.app"
echo "Your webhook URL will be: https://roofready-fulfillment.up.railway.app/webhooks/stripe"
echo ""
read -p "Press Enter when you have the URL..."

echo ""
echo "🔗 Step 7: Update Stripe Webhook"
echo "-------------------------------"
echo "1. Go to Stripe Dashboard → Webhooks"
echo "2. Edit your webhook endpoint"
echo "3. Update URL to: https://roofready-fulfillment.up.railway.app/webhooks/stripe"
echo "4. Save changes"
echo "5. Copy the 'Signing secret' (starts with whsec_)"
echo ""
echo "Then run:"
echo "railway variables set STRIPE_WEBHOOK_SECRET=YOUR_WEBSECRET_HERE"
echo ""
read -p "Press Enter after updating webhook..."

echo ""
echo "🧪 Step 8: Test the Setup"
echo "------------------------"
echo "1. Go to: https://roofready-seven.vercel.app"
echo "2. Click 'Book Demo' on any plan"
echo "3. Use test card: 4242 4242 4242 4242"
echo "4. Complete checkout"
echo "5. Check Railway logs: railway logs"
echo ""
echo "🎉 Deployment Complete!"
echo "======================"
echo ""
echo "Your RoofReady SaaS now has:"
echo "✅ Live fulfillment service"
echo "✅ Stripe webhook handling"
echo "✅ Post-payment automation"
echo "✅ Database integration"
echo ""
echo "Next: Add checkout buttons to your frontend!"
echo ""