#!/bin/bash

echo "🚀 RoofReady Stripe Setup Wizard"
echo "================================="
echo ""
echo "This script will guide you through setting up Stripe for RoofReady."
echo ""

# Check if .env file exists
if [ ! -f .env ]; then
    echo "⚠️  No .env file found. Creating from example..."
    cp .env.stripe.example .env
    echo "✅ Created .env file"
fi

echo ""
echo "📋 STEP 1: Create Stripe Account"
echo "--------------------------------"
echo "1. Go to: https://dashboard.stripe.com/register"
echo "2. Sign up for a free account"
echo "3. Once logged in, go to Developers → API keys"
echo ""
read -p "Press Enter when you have your Stripe account ready..."

echo ""
echo "🔑 STEP 2: Get API Keys"
echo "-----------------------"
echo "1. In Stripe Dashboard, go to Developers → API keys"
echo "2. Copy these two keys:"
echo "   - Publishable key (starts with pk_test_)"
echo "   - Secret key (starts with sk_test_)"
echo ""
read -p "Press Enter when you have both keys..."

echo ""
echo "💳 STEP 3: Create Products & Prices"
echo "-----------------------------------"
echo "We need to create 3 products in Stripe:"
echo ""
echo "1. RoofReady Starter - $99/month"
echo "2. RoofReady Pro - $199/month"  
echo "3. RoofReady Team - $349/month"
echo ""
echo "Manual creation steps:"
echo "1. Go to Products → Add Product"
echo "2. Name: 'RoofReady Starter'"
echo "3. Description: 'Small owner-operator teams'"
echo "4. Pricing: Recurring, $99/month"
echo "5. Save and note the Price ID (starts with price_)"
echo ""
echo "Repeat for Pro and Team plans."
echo ""
read -p "Press Enter when you have all 3 Price IDs..."

echo ""
echo "🌐 STEP 4: Set Up Webhooks"
echo "--------------------------"
echo "1. Go to Developers → Webhooks"
echo "2. Click 'Add endpoint'"
echo "3. Endpoint URL: https://roofready-fulfillment.up.railway.app/webhooks/stripe"
echo "4. Select events to listen for:"
echo "   - checkout.session.completed"
echo "   - customer.subscription.created"
echo "   - customer.subscription.updated"
echo "   - customer.subscription.deleted"
echo "   - invoice.paid"
echo "   - invoice.payment_failed"
echo "5. Click 'Add endpoint'"
echo "6. Copy the Signing secret (starts with whsec_)"
echo ""
read -p "Press Enter when webhook is configured..."

echo ""
echo "📝 STEP 5: Update Environment Variables"
echo "--------------------------------------"
echo "Open the .env file and update these values:"
echo ""
echo "STRIPE_PUBLISHABLE_KEY=your_pk_test_key"
echo "STRIPE_SECRET_KEY=your_sk_test_key"
echo "STRIPE_WEBHOOK_SECRET=your_whsec_key"
echo "STRIPE_PRICE_STARTER=your_starter_price_id"
echo "STRIPE_PRICE_PRO=your_pro_price_id"
echo "STRIPE_PRICE_TEAM=your_team_price_id"
echo ""
echo "Save the file when done."
echo ""
read -p "Press Enter when .env file is updated..."

echo ""
echo "✅ STEP 6: Test the Setup"
echo "-------------------------"
echo "To test your Stripe setup:"
echo ""
echo "1. Run: npm install stripe @supabase/supabase-js"
echo "2. Run: node test-stripe.js"
echo ""
echo "This will verify your API keys and create test customers."
echo ""

echo ""
echo "🎉 Setup Complete!"
echo "=================="
echo "Your RoofReady SaaS now has:"
echo "✅ Stripe account configured"
echo "✅ Products & prices created"
echo "✅ Webhooks set up"
echo "✅ Environment variables ready"
echo ""
echo "Next steps:"
echo "1. Deploy fulfillment service to Railway"
echo "2. Add Stripe checkout to your frontend"
echo "3. Test the complete payment flow"
echo ""
echo "Need help? Check:"
echo "📚 Stripe Docs: https://stripe.com/docs"
echo "🔧 RoofReady Docs: /DEPLOYMENT_GUIDE.md"
echo ""